### ISSUE TITLE
Bind data structures

### ISSUE THREAD

**Issue by bpalmeida** [freest-lang/freest3#117]
# Description

The `Bind` data type defined in the module `Syntax.Expression` is defined in an unnecessarily complicated way.

At this moment, we have:
```haskell
data Bind = Bind Pos Multiplicity ProgVar T.Type Exp
```

The only place where it is used is in the definition of term abstractions: `λ x:T -> e` and `λ x:T -o e`

```haskell
data Exp = 
    ...
  | Abs Pos Bind
    ...
```

The `Bind` should comprise information about the usage of the abstraction (their multiplicity). The suggestion is to remove the `Multiplicity` from the `Bind` datatype. Then, include it in the `Abs` data constructor.  The result will be something like this:

```haskell
data Exp = 
    ...
  | Abs Pos Multiplicity Bind
    ...

data Bind = Bind Pos ProgVar T.Type Exp
```

This simple change will allow joining the aforementioned `Bind` definition with the `Bind` definition from the module `Syntax.Kind`:
```haskell
data Bind a = Bind Pos TypeVar Kind a
```

which is used for term level type abstractions `Λ a:k => e`, for universal types `∀ a:k . T`, for recursive types `μ a:k . T`, and operator abstraction `λ a:k -> T` (branch type-ops).

```haskell
data Exp =
   ...
 | TypeAbs Pos (K.Bind Exp)   -- Λ a:k => e
   ...

data Type =
   ...
 | Forall Pos (K.Bind Type)   -- ∀ a:k . T, Universal type
 | Rec Pos (K.Bind Type)      -- μ a:k . T, Recursive type
 | Abs Pos (K.Bind Type)       -- λ a:k -> T, Operator abstraction
   ...
```

In the end, we should have a single `Bind` datatype:

```haskell

data Bind a b c = Bind Pos a b c 


data Exp =
   ...
 | Abs Pos Multiplicity (Bind ProgVar Type Exp)
 | TypeAbs Pos (Bind TypeVar Type Exp)   -- Λ a:k => e
   ...

data Type =
   ...
 | Forall Pos (Bind TypeVar Kind Exp)   -- ∀ a:k . T, Universal type
 | Rec Pos (Bind TypeVar Kind Exp)      -- μ a:k . T, Recursive type
 | Abs Pos (Bind TypeVar Kind Exp)       -- λ a:k -> T, Operator abstraction
   ...

```

As an alternative (and a good one, IMHO), we can use the record syntax:

```haskell

data Bind a b c = Bind {position :: Pos, var :: a, binder :: b, body :: c}

```

* **Note:** When working with records, the following language extensions might become handy:
  - Record puns
  - Record wildcards
  - (see [Record extensions](https://downloads.haskell.org/~ghc/9.0.1/docs/html/users_guide/exts/records.html))

# Task list 
1. [x] Remove `Multiplicity` from `E.Bind` and turn it into a constructor of `E.Abs`
2. [x] Join the different binds
   1. [x] Define the new bind and replace in each definition (type and expression)
   2. [x] Update all the code (pattern matching + instances of Bind)
   3. [x] Using the suggested record syntax imposes removing the function `body`. It clashes with the record field, and it has the same purpose.
