### ISSUE TITLE
Single representation for Variants, Choices and Records

### ISSUE THREAD

**Issue by bpalmeida** [freest-lang/freest3#120]
In GitLab by @gatpsilva on Apr 1, 2022, 05:50

Several branches of the definition of the `Type` data type in `Syntax.Type`, namely `Variant` and `Choice` express different types with essentially the same structure: a mapping between labels and types. The (previously) forthcoming `Record` branch, which would replace `Pair`, would also have this same structure.  
At the moment, we have:
```
data Type =
  ...
  | Variant Pos TypeMap
  ...
  | Choice Pos View TypeMap
```
and the introduction of `Record` would add:
```
  | Record Pos TypeMap
```
This is unnecessarily complicated.  
Taking this into account, we can simply combine the branches and factor out the differences between them into a new field that acts as a tag. This tag would also differentiate internal and external choices, rendering the `View` data type unnecessary (notice that it's a simple binary data type, defined as `data View = External | Internal deriving Eq`).  
This single branch has been tentatively called an `Almanac` and the data type for the tag field has been called a `Sort`.  
This would leave us with:
```
data Type =
  ...
  | Almanac Pos Sort TypeMap
  ...

data Sort = Record | Variant | ExtChoice | IntChoice deriving Eq
```
The names for these structures are up for discussion: `Sort` is loaded, and `Almanac`, in my opinion, obscures the meaning, evoking calendars and time measurement. The alternatives I can think of are `TypeMapping` and `MappingTag`, or something along those lines.  

## Task list:
1. [x] remove the Variant and Choice branches; introduce Almanac branch 
2. [x] remove View data type; define the Sort data type
3. [x] replace every use of Variant and Choice with Almanac
